# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.pdsm4dmp
canonical: https://interop.esante.gouv.fr/ig/fhir/pdsm4dmp # the last part of canonical and id must be the same
name: PDSm4DMP # Should be an acronym
title: Utilisation de PDSm pour le DMP dans le contexte d'EEDS
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build # le release label doit être conforme au cycle de vie de la doctrine du ci-sis
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

dependencies:
    ans.fr.terminologies: latest
    ans.fhir.fr.pdsm: 3.1.0
    hl7.fhir.fr.core: 2.1.0

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'
    path-resource:
         input/Examples
        #- input/fsh/data-type/primitive/complex/complex-data-type

pages:
    index.md:
        title: Accueil
    specifications_techniques.md:
        construction_des_flux.md:
        transaction_1.md:
            title: Flux 01
        transaction_2.md:
            title: Flux 02
        transaction_td02.md:
            title: Flux TD02
        transaction_td2.md:
            title: Flux TD2          
        transaction_td2.1.md:
            title: Flux TD2.1             
        transaction_td3.1a.md:
            title: Flux TD3.1a           
        transaction_td3.1b.md:
            title: Flux TD3.1b
        transaction_td3.2.md:
            title: Flux TD3.2                        
        transaction_td3.3a.md:
            title: Flux TD3.3a      
        transaction_td3.3b.md:
            title: Flux TD3.3b      
        transaction_td3.3c.md:
            title: Flux TD3.3c                             
        transaction_td3.3d.md:
            title: Flux TD3.3d      
    exemples_usage_dmp.md:
        title: Exemples d'usages DMP
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages


menu:
    Accueil: index.html
    Transaction DMP Patient:
        Diagramme: construction_des_flux.html
        Transaction TD02: transaction_td02.html      
        Transaction TD2: transaction_td2.html     
        Transaction TD2.1: transaction_td2.1.html  
        Transaction TD3.1a: transaction_td3.1a.html     
        Transaction TD3.1b: transaction_td3.1b.html 
        Transaction TD3.2: transaction_td3.2.html       
        Transaction TD3.3a: transaction_td3.3a.html      
        Transaction TD3.3b: transaction_td3.3b.html     
        Transaction TD3.3c: transaction_td3.3c.html 
        Transaction TD3.3d: transaction_td3.3d.html             


    Exemples d'usages DMP: exemples_usage_dmp.html 
    Ressources de conformité: artifacts.html
    Autres ressources:
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/

resources:


#------------ Examples -----------
  Binary/AuthorPSCabinetRPPS:
    profile: StructureDefinition/AuthorPersonPS

  Binary/AuthorStructure:
    profile: StructureDefinition/AuthorPersonPS

  Binary/AuthorDispositif:
    profile: StructureDefinition/AuthorPersonSystem

  Binary/AuthorPatient:
    profile: StructureDefinition/AuthorPersonPatient


groups:
  LogicalModel:
    name:  Model Logique SubmissionSet et  DocumentEntry (XDS)
    description: Model Logique  SubmissionSet et  DocumentEntry XDS
    resources:
      - StructureDefinition/SubmissionSet
      - StructureDefinition/DocumentEntry      
      - StructureDefinition/EventCode      

  LogicalModelPatient:
    name:  Model Logique Patient (XDS)
    description: Model Logique Patient XDS
    resources:
      - StructureDefinition/PatientId
      - StructureDefinition/SourcePatientId
      - StructureDefinition/SourcePatientInfo


  LogicalModelAuthor:
    name:  Model Logique Author et LegalAuthenticator (XDS)
    description: Model Logique Author et LegalAuthenticator XDS
    resources:
      - StructureDefinition/LegalAuthenticator
      - StructureDefinition/Author
      - StructureDefinition/AuthorInstitution
      - StructureDefinition/AuthorPerson            
      - StructureDefinition/AuthorPersonPS
      - StructureDefinition/AuthorPersonPatient
      - StructureDefinition/AuthorPersonSNR
      - StructureDefinition/AuthorPersonSystem   

  DataType:
    name:  Data Type 
    description: Type de base du Model Logique
    resources:
      - StructureDefinition/IdentifiantSysteme
      - StructureDefinition/MatriculeINS
      - StructureDefinition/PSIdNat
      - StructureDefinition/SNR            
      - StructureDefinition/StructIdNat



  mapping:
    name:  Mapping Volet partage vers PDSM
    description: Mapping du "Volet Partage de Documents de Santé"   vers "Partage de Documents de Santé en mobilité (PDSm)""
    resources:
      - ConceptMap/documentReferenceToPDSM
      - ConceptMap/submissionSetToPDSM


  exemple:
    name:  Liste d'exemples
    description: Liste des exemples 
    resources:
      - Binary/AuthorPatient
      - Binary/AuthorDispositif
      - Binary/AuthorStructure
      - Binary/AuthorPSCabinetRPPS
