# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.pdsm4dmp
canonical: https://interop.esante.gouv.fr/ig/fhir/pdsm4dmp # the last part of canonical and id must be the same
name: PDSm4DMP # Should be an acronym
title: Utilisation de PDSm pour le DMP dans le contexte d'EEDS
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build # le release label doit être conforme au cycle de vie de la doctrine du ci-sis
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

dependencies:
    ans.fr.terminologies: latest
    ans.fhir.fr.pdsm: 3.1.0
    hl7.fhir.fr.core: 2.1.0

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'
    path-resource:
         input/Examples
        #- input/fsh/data-type/primitive/complex/complex-data-type

pages:
    index.md:
        title: Accueil


menu:
    Accueil: index.html
    Artifacts: artifacts.html